In [2]:
# 1. Импортировать NumPy
import numpy as np

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [44]:
# Ваш код
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
#np.random.seed(42)  # для воспроизводимости результатов
array = np.random.randint(1, 101, size=(10, 10), dtype=np.int64)

print("1.1 Исходный массив 10x10:")
print(array)
print("\n" + "="*50 + "\n")

1.1 Исходный массив 10x10:
[[ 76  26  16  51  86  57  29  78  92  69]
 [ 47  94  62  69  76  16  90  90  48  85]
 [ 39 100  33  94  23  10  69 100  34  52]
 [ 95  10  19  58  96   1  69   4  16  24]
 [ 80   2  92  32  91  84  24  12  50  35]
 [ 33  33  61  51  43  12  67  65  33  40]
 [ 74  43  44  29  13  12  95  46   2  35]
 [ 87  81  90   8  93  26  74  90  34   7]
 [ 68  58  75  29  36  89  21  36  10  73]
 [ 24  64  99  49  99  36  82  96  24  23]]




In [48]:
# 1.2 Вычислить среднее значение всех элементов массива
total_mean = np.mean(array)
print(f"1.2 Среднее значение всех элементов: {total_mean:.2f}")
print("\n" + "="*50 + "\n")

1.2 Среднее значение всех элементов: 52.17




In [49]:
# 1.3 Вычислить среднее значение для каждой строки и добавить как новый столбец
row_means = np.mean(array, axis=1, keepdims=True)
array_with_row_means = np.hstack((array, row_means))

print("1.3 Массив с добавленным столбцом средних значений строк:")
# Форматированный вывод с заголовками столбцов
print("Столбцы 1-10".ljust(12), "Среднее".ljust(10))
for i, row in enumerate(array_with_row_means, 1):
    cols = " ".join(f"{x:3}" for x in row[:-1])
    mean = f"{row[-1]:6.2f}"
    print(f"Строка {i:2}: {cols} | {mean}")
print("\n" + "="*50 + "\n")

1.3 Массив с добавленным столбцом средних значений строк:
Столбцы 1-10 Среднее   
Строка  1: 76.0 26.0 16.0 51.0 86.0 57.0 29.0 78.0 92.0 69.0 |  58.00
Строка  2: 47.0 94.0 62.0 69.0 76.0 16.0 90.0 90.0 48.0 85.0 |  67.70
Строка  3: 39.0 100.0 33.0 94.0 23.0 10.0 69.0 100.0 34.0 52.0 |  55.40
Строка  4: 95.0 10.0 19.0 58.0 96.0 1.0 69.0 4.0 16.0 24.0 |  39.20
Строка  5: 80.0 2.0 92.0 32.0 91.0 84.0 24.0 12.0 50.0 35.0 |  50.20
Строка  6: 33.0 33.0 61.0 51.0 43.0 12.0 67.0 65.0 33.0 40.0 |  43.80
Строка  7: 74.0 43.0 44.0 29.0 13.0 12.0 95.0 46.0 2.0 35.0 |  39.30
Строка  8: 87.0 81.0 90.0 8.0 93.0 26.0 74.0 90.0 34.0 7.0 |  59.00
Строка  9: 68.0 58.0 75.0 29.0 36.0 89.0 21.0 36.0 10.0 73.0 |  49.50
Строка 10: 24.0 64.0 99.0 49.0 99.0 36.0 82.0 96.0 24.0 23.0 |  59.60




In [50]:
# 1.4 Вычислить сумму значений для каждого столбца и добавить как новую строку
column_sums = np.sum(array_with_row_means, axis=0, keepdims=True)
final_array = np.vstack((array_with_row_means, column_sums))

print("1.4 Итоговый массив с суммами столбцов в последней строке:")
# Форматированный вывод с заголовками
header = " ".join(f"Col{i:2}" for i in range(1, 11)) + "  Mean"
print(header)
print("-"*len(header))

for i, row in enumerate(final_array[:-1], 1):
    print(f"Row{i:2} " + " ".join(f"{x:4}" for x in row))

print("-"*len(header))
print("Sum  " + " ".join(f"{int(x):4}" for x in final_array[-1]))

1.4 Итоговый массив с суммами столбцов в последней строке:
Col 1 Col 2 Col 3 Col 4 Col 5 Col 6 Col 7 Col 8 Col 9 Col10  Mean
-----------------------------------------------------------------
Row 1 76.0 26.0 16.0 51.0 86.0 57.0 29.0 78.0 92.0 69.0 58.0
Row 2 47.0 94.0 62.0 69.0 76.0 16.0 90.0 90.0 48.0 85.0 67.7
Row 3 39.0 100.0 33.0 94.0 23.0 10.0 69.0 100.0 34.0 52.0 55.4
Row 4 95.0 10.0 19.0 58.0 96.0  1.0 69.0  4.0 16.0 24.0 39.2
Row 5 80.0  2.0 92.0 32.0 91.0 84.0 24.0 12.0 50.0 35.0 50.2
Row 6 33.0 33.0 61.0 51.0 43.0 12.0 67.0 65.0 33.0 40.0 43.8
Row 7 74.0 43.0 44.0 29.0 13.0 12.0 95.0 46.0  2.0 35.0 39.3
Row 8 87.0 81.0 90.0  8.0 93.0 26.0 74.0 90.0 34.0  7.0 59.0
Row 9 68.0 58.0 75.0 29.0 36.0 89.0 21.0 36.0 10.0 73.0 49.5
Row10 24.0 64.0 99.0 49.0 99.0 36.0 82.0 96.0 24.0 23.0 59.6
-----------------------------------------------------------------
Sum   623  511  591  470  656  343  620  617  343  443  521


#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули.
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [52]:
# Ваш код
diagonal_values = np.array([1, 2, 3, 4, 5, 6, 7])
matrix_diag = np.diag(diagonal_values)

print("Вариант 1 (с np.diag()):")
print(matrix_diag)


Вариант 1 (с np.diag()):
[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [53]:
rows, cols = np.indices((7, 7))
matrix_broadcast = np.where(rows == cols, rows + 1, 0)  # rows+1 дает значения 1-7

print("\nВариант 2 (с broadcasting):")
print(matrix_broadcast)


Вариант 2 (с broadcasting):
[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [55]:
# Ваш код
# Создаем случайную матрицу 5x7 с целыми числами от 1 до 100
matrix = np.random.randint(1, 101, size=(5, 7))

print("Исходная матрица:")
print(matrix)

# Меняем местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки
matrix[:, [2, 4]] = matrix[:, [4, 2]]

print("\nМатрица после замены колонок:")
print(matrix)

Исходная матрица:
[[ 25  52  85 100  53  23  16]
 [ 57  39  53  42  58  39  14]
 [ 95   5  35  87  93  75  18]
 [ 76   9  74  58  17   7  46]
 [ 13  40  42   9  50  27  66]]

Матрица после замены колонок:
[[ 25  52  53 100  85  23  16]
 [ 57  39  58  42  53  39  14]
 [ 95   5  93  87  35  75  18]
 [ 76   9  17  58  74   7  46]
 [ 13  40  50   9  42  27  66]]
