## Анализ и визуализация данных на языке Python.

In [1]:
import numpy as np
np.set_printoptions(linewidth=110, legacy="1.25") # Для вывода чисел без явного указания типа

#### Нужные параметры для вывода всех значений, а не только последнего(по умолчанию)

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"     # Вывод всех строк без принтов
# InteractiveShell.ast_node_interactivity = "last"  # Только последний вывод

### Изменение размерности

Функции __ravel()__, __reshape()__, __flatten()__ и __resize()__

In [ ]:
import numpy as np

In [3]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
# Результат - одномерный массив
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [5]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
b.flatten() # возращает копию

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
b.shape
b.shape = (6, 4)  ## то же самое, что и b.reshape(6, 4)
b.shape

(2, 3, 4)

(6, 4)

In [9]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
# Транспонирование матрицы: строки -> столбцы, столбцы -> строки
# можно и так b.T
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [11]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
# https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.as_strided.html
# Warning: This function has to be used with extreme care, see notes.
b = np.arange(24).reshape(2, 3, 4)
b
b.strides # Смещение в байтах каждой оси(измерения)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(96, 32, 8)

In [13]:
# 1-е измерение становится 0-м, второе - первым, нулевое - вторым
new_b = b.transpose(1, 2, 0)
new_b
new_b.strides

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

(32, 8, 96)

#### Изменение размера массива

In [14]:
d = np.random.randint(1, 100, (2, 12)); d

array([[82,  5, 45, 93, 24, 56, 40, 69, 39, 48, 84, 40],
       [ 1, 71, 76, 89,  2, 19, 71, 64, 72, 40, 92, 74]])

In [15]:
# resize() как метод - новые элементы заполнены нулями
d.resize((3, 15), refcheck=False); d

array([[82,  5, 45, 93, 24, 56, 40, 69, 39, 48, 84, 40,  1, 71, 76],
       [89,  2, 19, 71, 64, 72, 40, 92, 74,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [16]:
c = np.arange(24)
c.shape = 8, 3
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
c.resize(9, 3, refcheck=False)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0]])

In [18]:
c.resize?

In [19]:
## Новые элементы массива будут иметь значение 0,
## когда вызываем у массива
c1 = c.copy()
c1.resize(15, 3)
c1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [20]:
c.shape
# resize() как функция numpy - новые элементы массива берут значения из старого массива
c2 = np.resize(c, (12, 3))
c2

(9, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

### Добавление элементов. Оси(axes).

In [21]:
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.append(a, [1, 3, 4, 4]); a   # Похож на метод extend для списка

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 4])

In [23]:
e = np.arange(12).reshape(3, 4); e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# 0-я ось - это строки в 2-мерном массиве
e = np.append(e, [[99, 97, 96, 95]], axis=0)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [99, 97, 96, 95]])

In [25]:
e = np.append(e, [[99],
                  [97],
                  [96],
                  [95]], axis=1) # 1-я ось - это столбцы в 2-мерном массиве
e

array([[ 0,  1,  2,  3, 99],
       [ 4,  5,  6,  7, 97],
       [ 8,  9, 10, 11, 96],
       [99, 97, 96, 95, 95]])

In [26]:
temp = np.array([[99, 97, 96, 95]]); temp

array([[99, 97, 96, 95]])

In [27]:
temp.shape

(1, 4)

In [28]:
temp1 = np.array([[99], [97], [96], [95]]); temp1

array([[99],
       [97],
       [96],
       [95]])

In [29]:
temp1.shape

(4, 1)

In [30]:
a3d = np.arange(27).reshape(3, 3, 3); a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
add_mas = np.arange(100, 109).reshape(3, 3, 1); add_mas

array([[[100],
        [101],
        [102]],

       [[103],
        [104],
        [105]],

       [[106],
        [107],
        [108]]])

In [32]:
a3d_new = np.append(a3d, add_mas, axis=2)   # 0-я ось - это глубина
a3d_new

array([[[  0,   1,   2, 100],
        [  3,   4,   5, 101],
        [  6,   7,   8, 102]],

       [[  9,  10,  11, 103],
        [ 12,  13,  14, 104],
        [ 15,  16,  17, 105]],

       [[ 18,  19,  20, 106],
        [ 21,  22,  23, 107],
        [ 24,  25,  26, 108]]])

In [33]:
vector = np.array([[4, 5, 6]])
vector, vector.shape

(array([[4, 5, 6]]), (1, 3))

In [34]:
foo = np.append(a3d_new, vector, 0); foo ## Error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

### Вставка элементов

In [35]:
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 2 - это индекс элемента, но не значение
# при вставке изменился тип элементов на тип массива
a = np.insert(a, 2, np.asarray([99.7, 101.09])); a

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [37]:
# Вставка в массив NxM
a1 = np.array([[1, 1], [2, 2], [3, 3]])
a1

array([[1, 1],
       [2, 2],
       [3, 3]])

In [38]:
np.insert(a1, 4, 5)  # Сейчас массив будет представлен в виде единой ленточки(flatten)

array([1, 1, 2, 2, 5, 3, 3])

In [39]:
# Явно указали ось(измерение), по которой работаем(столбцы) и получили вектор из 5-ок
np.insert(a1, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [40]:
a

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [41]:
## Hовые элементы неявно будет преобразованы к типу элементов массива
a = np.insert(a, 6, np.random.randn(10) * 3); a

array([  0,   1,  99, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,   5,   6,   7,
         8,   9])

In [42]:
a
new_a = np.insert(a, 2, [20, 21, 22], axis=0); new_a

array([  0,   1,  99, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,   5,   6,   7,
         8,   9])

array([  0,   1,  20,  21,  22,  99, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,
         5,   6,   7,   8,   9])

### Удаление элементов

In [43]:
a
np.delete(a, 2, axis=0) # a[2, :]

array([  0,   1,  99, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,   5,   6,   7,
         8,   9])

array([  0,   1, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,   5,   6,   7,   8,
         9])

In [44]:
a
np.delete(a, 2, axis=1)

array([  0,   1,  99, 101,   2,   3,   1,   0,   5,   0,  -9,   0,   7,   1,   0,   4,   4,   5,   6,   7,
         8,   9])

AxisError: axis 1 is out of bounds for array of dimension 1