## Анализ и визуализация данных на языке Python.

In [1]:
import numpy as np

In [2]:
np.set_printoptions(linewidth=110, legacy="1.25")

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Стекинг(Stacking)

Function|Description
---|:---
vstack()|Функция соединяет массивы вертикально
row_stack()|Функция соединяет массивы вертикально
hstack()|Функция соединяет массивы горизонтально
dstack()|Функция соединяет массивы в глубину, используя третье измерение(ось)
column_stack()|Функция соединяет одномерные массивы как колонки в двумерном массиве
concatenate()|Функция соединяет список или кортеж массивов

In [4]:
a = np.arange(9).reshape(3, 3); a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
b = 2 * a; b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [6]:
# объединяем по горизонтали, аргументы должны быть указаны в виде кортежа!
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [7]:
np.hstack((a, np.arange(100, 124).reshape(3, 8)))

array([[  0,   1,   2, 100, 101, 102, 103, 104, 105, 106, 107],
       [  3,   4,   5, 108, 109, 110, 111, 112, 113, 114, 115],
       [  6,   7,   8, 116, 117, 118, 119, 120, 121, 122, 123]])

In [8]:
np.hstack((a, a, b, b))

array([[ 0,  1,  2,  0,  1,  2,  0,  2,  4,  0,  2,  4],
       [ 3,  4,  5,  3,  4,  5,  6,  8, 10,  6,  8, 10],
       [ 6,  7,  8,  6,  7,  8, 12, 14, 16, 12, 14, 16]])

In [9]:
# Та же самая операция
# Строки - это axis(ось)=0, столбцы - это axis(ось)=1
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [10]:
np.vstack((a, np.arange(100, 124).reshape(8, 3))) # по вертикали

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111],
       [112, 113, 114],
       [115, 116, 117],
       [118, 119, 120],
       [121, 122, 123]])

In [11]:
np.vstack((a, b, a * 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [12]:
# Та же самая операция
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
a3d1 = np.arange(1, 25).reshape(2, 3, 4); a3d1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
a3d2 = np.arange(100, 136).reshape(3, 3, 4)
a3d2

array([[[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123]],

       [[124, 125, 126, 127],
        [128, 129, 130, 131],
        [132, 133, 134, 135]]])

In [15]:
res = np.vstack((a3d1, a3d2)); res

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]],

       [[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123]],

       [[124, 125, 126, 127],
        [128, 129, 130, 131],
        [132, 133, 134, 135]]])

In [16]:
res.shape

(5, 3, 4)

In [17]:
a, b

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

In [18]:
np.dstack((a, b)) # axis=2 - это новая новая ось, результат "склейки"

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [19]:
np.dstack((a, b)).transpose(2, 0, 1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]])

In [20]:
c1 = np.arange(12).reshape(3, 4); c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
c2 = np.arange(100, 112).reshape(3, 4); c2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [22]:
np.dstack((c1, c2)) # deep stack объединяет по глубине. Добавляем новое измерение

array([[[  0, 100],
        [  1, 101],
        [  2, 102],
        [  3, 103]],

       [[  4, 104],
        [  5, 105],
        [  6, 106],
        [  7, 107]],

       [[  8, 108],
        [  9, 109],
        [ 10, 110],
        [ 11, 111]]])

In [23]:
np.dstack((a3d1, a3d2))  # Error

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [24]:
np.row_stack((a, b))

<ipython-input-24-f4983b79349c>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### Проверка на равенство элементов

In [25]:
np.row_stack((a, b)) == np.vstack((a, b))  # матрица True, shape=(6,3)

<ipython-input-25-d719708ed006>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b)) == np.vstack((a, b))  # матрица True, shape=(6,3)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
a == b

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [27]:
res = a == b
type(res), res.dtype

(numpy.ndarray, dtype('bool'))

In [28]:
# np.all() вернет Тrue, если все элементы массива True, иначе False
# np.any() вернет Тrue, если хотя бы один элемент массива True иначе False
np.all(a == b), np.any(a == b)

(False, True)

In [29]:
np.all(np.row_stack((a, b)) == np.vstack((a, b)))

<ipython-input-29-2172ea76305a>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.all(np.row_stack((a, b)) == np.vstack((a, b)))


True

In [30]:
c = np.arange(2); c

array([0, 1])

In [31]:
twice_c = 2 * c; twice_c

array([0, 2])

In [32]:
np.column_stack((c, twice_c))

array([[0, 0],
       [1, 2]])

In [33]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [34]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

### Разделение (Splitting).
#### hsplit(), vsplit(), dsplit(), split()

In [35]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
a2 = np.arange(1, 13).reshape(3, 4); a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
# Разделяет на три массива по горизонтальной оси
# Второй аргумент - это количество частей(матриц)
res1, res2, res3 = np.hsplit(a, 3); res1.shape

(3, 1)

In [38]:
a
np.hsplit(a, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [39]:
a2
# Разделяет на два массива по горизонтальной оси
np.hsplit(a2, 2)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [40]:
np.hsplit(a, 2) # Error

ValueError: array split does not result in an equal division

In [41]:
# то же самое, что и np.hsplit(a, 3)
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [42]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
# Разделяет на три массива по вертикальной оси
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [44]:
a1, a2, a3 = np.vsplit(a, 3)

In [45]:
a1

array([[0, 1, 2]])

In [46]:
a1.shape

(1, 3)

In [47]:
# то же самое, что и np.vsplit(a, 3)
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [48]:
c = np.arange(27).reshape(3, 3, 3); c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [49]:
np.dsplit(c, 3) # С двумерными массивами выдаст ошибку

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [50]:
c1, c2, c3 = np.dsplit(c, 3)

In [51]:
c1

array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]])

In [52]:
c1.shape
c1.transpose(2, 0, 1)

(3, 3, 1)

array([[[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]]])

### Деление на ноль и np.nan

In [53]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
a / 0

<ipython-input-54-4f74cdd1c1e6>:1: RuntimeWarning: divide by zero encountered in divide
  a / 0
<ipython-input-54-4f74cdd1c1e6>:1: RuntimeWarning: invalid value encountered in divide
  a / 0


array([[nan, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [55]:
print(1 * np.nan)
print(np.nan + 5)
print(4 < np.nan)
print(4 > np.nan)
print("=" * 30)
print(np.nan == np.nan)  # False
print(np.nan is np.nan)  # True
print(np.inf > np.nan)
print(np.nan - np.nan)
print('=' * 30)
print(np.nan in set([np.nan]))
s = set([frozenset(), 4])
s

nan
nan
False
False
False
True
False
nan
True


{4, frozenset()}

In [56]:
id(np.nan)

135826192333968

In [57]:
a = np.array([4, 9, 2, np.nan])
np.isnan(a)
np.isnan(a).any()
# Если есть хоть один nan, необходимо вызывать функции, в которых добавляется nan
# np.nanmin, np.nansum, etc
np.min(a)
np.nanmin(a)

array([False, False, False,  True])

True

nan

2.0

### Создание фиктивных осей

In [58]:
d = np.random.randn(6)
d

array([ 0.10404218, -0.20903785,  0.50630784, -0.66928985,  0.67104666, -0.75114575])

In [59]:
d.shape

(6,)

In [60]:
d.ndim

1

In [61]:
# Создание фиктивных осей: можно np.newaxis можно None
d1 = d[:, np.newaxis, None]
d1

array([[[ 0.10404218]],

       [[-0.20903785]],

       [[ 0.50630784]],

       [[-0.66928985]],

       [[ 0.67104666]],

       [[-0.75114575]]])

In [62]:
d1.ndim, d1.shape

(3, (6, 1, 1))

In [63]:
d2 = d[None, :, None]
d2.shape
d2

(1, 6, 1)

array([[[ 0.10404218],
        [-0.20903785],
        [ 0.50630784],
        [-0.66928985],
        [ 0.67104666],
        [-0.75114575]]])

In [64]:
d3 = d[None, None, :]
d3.shape

(1, 1, 6)

In [65]:
d3

array([[[ 0.10404218, -0.20903785,  0.50630784, -0.66928985,  0.67104666, -0.75114575]]])

In [66]:
m1 = np.ones((3, 4));m1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
m1_new = m1[np.newaxis, :, :]

In [68]:
m1_new.shape

(1, 3, 4)

In [69]:
m1_new

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [70]:
m1[:, :, None].shape # (3, 4, 1)
m1[:, :, None]

(3, 4, 1)

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [71]:
m2 = np.ones((3, 5));m2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
m2[:, None, :]  # (3, 1, 5)

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

### Broadcast

![first.PNG](attachment:first.PNG)

![second.PNG](attachment:second.PNG)

![third.PNG](attachment:third.PNG)

In [73]:
m1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
m2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
# m1[0] *= 5
# m1[1] *= 2
m1
# m2 = m2 * 3
m2
m3 = m1[:, :, None] + m2[:, None, :] # (3, 4, 1) + (3, 1, 5)
m3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [76]:
m3.shape

(3, 4, 5)

In [77]:
d

array([ 0.10404218, -0.20903785,  0.50630784, -0.66928985,  0.67104666, -0.75114575])

In [78]:
# Создать фиктивную ось для строк
new_d2 = np.expand_dims(d, axis=0); new_d2

array([[ 0.10404218, -0.20903785,  0.50630784, -0.66928985,  0.67104666, -0.75114575]])

In [79]:
new_d2.shape

(1, 6)

In [80]:
# Можно, но не рекомендую
d.reshape(*d.shape, 1) # d[..., np.newaxis]

array([[ 0.10404218],
       [-0.20903785],
       [ 0.50630784],
       [-0.66928985],
       [ 0.67104666],
       [-0.75114575]])

In [81]:
d[:, np.newaxis, np.newaxis].shape

(6, 1, 1)

In [82]:
arr1 = np.full((3, 3), 2); arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [83]:
arr2 = np.arange(10, 13); arr2

array([10, 11, 12])

In [84]:
arr2 = arr2[None, :]; arr2   # Фиктивная ось для строк. Лучше делать это явно!

array([[10, 11, 12]])

In [85]:
arr1
arr2
arr1 + arr2  # broadcasting: (1, 3) -> (3, 3) -> (3, 3) + (3, 3)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

array([[10, 11, 12]])

array([[12, 13, 14],
       [12, 13, 14],
       [12, 13, 14]])

In [86]:
arr3 = np.arange(10, 13)
arr3 = arr3[:, None]; arr3   # Фиктивная ось для столбцов

array([[10],
       [11],
       [12]])

In [87]:
arr1 + arr3

array([[12, 12, 12],
       [13, 13, 13],
       [14, 14, 14]])

In [88]:
ex1 = np.arange(24).reshape(2, 3, 4)
ex1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
ex1
ex1 + np.arange(100, 102)[:, None, None]  # (2, 3, 4) + (2, 1, 1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[113, 114, 115, 116],
        [117, 118, 119, 120],
        [121, 122, 123, 124]]])

### Удаление фиктивных осей

In [90]:
d1, d1.shape

(array([[[ 0.10404218]],
 
        [[-0.20903785]],
 
        [[ 0.50630784]],
 
        [[-0.66928985]],
 
        [[ 0.67104666]],
 
        [[-0.75114575]]]),
 (6, 1, 1))

In [91]:
# Удалить лишнее оси
new_d1 = np.squeeze(d1)
new_d1

array([ 0.10404218, -0.20903785,  0.50630784, -0.66928985,  0.67104666, -0.75114575])

## Операции между массивами и скалярами.


#### Операции выполняются поэлементно

In [92]:
vec = np.arange(1, 7).reshape(2, 3); vec

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
2 + vec

array([[3, 4, 5],
       [6, 7, 8]])

In [94]:
vec * vec

array([[ 1,  4,  9],
       [16, 25, 36]])

In [95]:
vec - vec

array([[0, 0, 0],
       [0, 0, 0]])

In [96]:
# Тип элементов при делении всегда np.float64
1 / vec

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [97]:
a = vec ** 0.5
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Унарные операции
- abs, fabs (для вещественных)
- sqrt, square,
- exp, log, log10, log2,
- sign, ceil, floor, rint,
- modf,
- isnan, isinf,
- cos, sin и т.д.

In [98]:
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [99]:
## Приводит значения вперед к ближайшему целому
np.ceil(a)

array([[1., 2., 2.],
       [2., 3., 3.]])

In [100]:
## Приводит значения назад к ближайшему целому
np.floor(a)

array([[1., 1., 1.],
       [2., 2., 2.]])

In [101]:
a_minus = -a
a_minus

array([[-1.        , -1.41421356, -1.73205081],
       [-2.        , -2.23606798, -2.44948974]])

In [102]:
7 / 3

2.3333333333333335

In [103]:
7 // 3

2

In [104]:
a_minus // 2
-7 // 3 # -3
-7 % 3 # 2
-7 == 3 * (-3) + 2

array([[-1., -1., -1.],
       [-1., -2., -2.]])

-3

2

True

In [105]:
a_minus
np.ceil(a_minus)

array([[-1.        , -1.41421356, -1.73205081],
       [-2.        , -2.23606798, -2.44948974]])

array([[-1., -1., -1.],
       [-2., -2., -2.]])

In [106]:
np.floor(a_minus)

array([[-1., -2., -2.],
       [-2., -3., -3.]])

In [107]:
np.info(np.rint)

rint(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Round elements of the array to the nearest integer.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For other keyword-only ar

In [108]:
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [109]:
np.rint(a)
np.rint(np.array([3.5, 4.5, 5.5, 6.500000000000001, 13 / 2]))

array([[1., 1., 2.],
       [2., 2., 2.]])

array([4., 4., 6., 7., 6.])

In [110]:
## Результат - это два отдельных массива, целые и дробные части
np.modf(a)

(array([[0.        , 0.41421356, 0.73205081],
        [0.        , 0.23606798, 0.44948974]]),
 array([[1., 1., 1.],
        [2., 2., 2.]]))

In [111]:
res1, res2 = np.modf(a)
res1
np.isnan(res1 / 0), np.isinf(res1 / 0)

array([[0.        , 0.41421356, 0.73205081],
       [0.        , 0.23606798, 0.44948974]])

<ipython-input-111-7f11c6860736>:3: RuntimeWarning: divide by zero encountered in divide
  np.isnan(res1 / 0), np.isinf(res1 / 0)
<ipython-input-111-7f11c6860736>:3: RuntimeWarning: invalid value encountered in divide
  np.isnan(res1 / 0), np.isinf(res1 / 0)


(array([[ True, False, False],
        [ True, False, False]]),
 array([[False,  True,  True],
        [False,  True,  True]]))

## Бинарные операции

### <center> Математические операции  </center>

Функция | Операция
---|---
np.add(m1, m2) |  +
np.multiply(m1, m2) | *
np.subtract(m1, m2) | -
np.divide(m1, m2) | /
np.power(m1, m2) | **
np.floor_divide(m1, m2) | //

In [112]:
n = np.arange(4)
n1 = np.arange(4, 8).reshape(4, 1)
print(n)
print(n.shape)
print(n1)
print(n1.shape)

[0 1 2 3]
(4,)
[[4]
 [5]
 [6]
 [7]]
(4, 1)


In [113]:
n1
n
np.add(n1, n)  # Неявно n приводится к размерности(1, 4)

array([[4],
       [5],
       [6],
       [7]])

array([0, 1, 2, 3])

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [114]:
np.add(n, n1)

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [115]:
m1 = np.arange(2,14).reshape(3, 4); m1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [116]:
m2 = np.arange(12).reshape(3, 4)
m2[0,0] = 1
m2[2,3] = 14
m2

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 14]])

In [117]:
np.divide(m1, m2)

array([[2.        , 3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333, 1.28571429],
       [1.25      , 1.22222222, 1.2       , 0.92857143]])

In [118]:
## Целочисленное деление
np.floor_divide(m1, m2)
m1 // m2

array([[2, 3, 2, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0]])

array([[2, 3, 2, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0]])

In [119]:
np.power(m1, m2, dtype=np.int64)

array([[               2,                3,               16,              125],
       [            1296,            16807,           262144,          4782969],
       [       100000000,       2357947691,      61917364224, 3937376385699289]])

### Операторы сравнения

Функция | Операция
---|---
greater | >
greater_equal |>=
less | <
less_equal | <=
equal| ==
not_equal | !=
logical_and | &
logical_or | \|
logical_xor | \^



- np.maximum(m1, m2) и np.minimum(m1,m2) - поэлементнo
- np.fmax(m1, m2) и np.fmin(m1,m2) - игнорируют значение NaN

**операторы Python: and, or, not не поддерживаются!**

In [120]:
m1
m2
#### Из каждой пары элементов выбирает наибольший
np.maximum(m1, m2)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 14]])

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 14]])

In [121]:
np.minimum(m1, m2)

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 13]])

In [122]:
m3 = np.arange(100, 103).reshape(3, 1); m3

array([[100],
       [101],
       [102]])

In [123]:
m4 = m1.copy()
m4[0,3] = 101
m4

array([[  2,   3,   4, 101],
       [  6,   7,   8,   9],
       [ 10,  11,  12,  13]])

### broadcasing выполняется при двух условиях:
1. Либо размерности совпадают
2. Либо одна из размерностей равна 1

In [124]:
m3
m4
m4 > m3 # broadcasting

array([[100],
       [101],
       [102]])

array([[  2,   3,   4, 101],
       [  6,   7,   8,   9],
       [ 10,  11,  12,  13]])

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [125]:
m1
m2
m1 > m2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 14]])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [126]:
m1 < m2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

#### <center>Логическое $ИЛИ$ над двумя массивами, операция: $|$ </center>
Правый операнд | Левый операнд | Результат
---|---|---
True | False| True
False | True | True
True | True | True
False | False| False

In [127]:
(m1 > m2) | (m1 < m2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### <center>Логическое $И$ над двумя массивами, операция: $&$ </center>
Правый операнд | Левый операнд | Результат
---|---|---
False | False| False
True | False| False
False | True | False
True | True | True

In [128]:
(m1 > m2) & (m1 < m2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

#### <center>Логическое $xor$ над двумя массивами, операция: $^$ </center>
Правый операнд | Левый операнд | Результат
---|---|---
False | False| False
True | False| True
False | True | True
True | True | False

In [129]:
a = np.array([[True, False, True], [True, True, False]]); a

array([[ True, False,  True],
       [ True,  True, False]])

In [130]:
b = np.array([[True, True, True], [False, True, False]]); b

array([[ True,  True,  True],
       [False,  True, False]])

In [131]:
a ^ b

array([[False,  True, False],
       [ True, False, False]])

#### Инверсия (тильда)

In [132]:
m1 > m2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [133]:
~(m1 > m2)  # not, отрицание

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [134]:
~(m1 > m2) == (m2 > m1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])