## Библиотека numpy

### Практика 1

In [2]:
# загрузите необходимые библиотеки
import numpy as np

### Задачи

Решите следующие задачи без использования циклов, с минимальным количеством строк.

1 . Решите следующие небольшие задачи

In [7]:
# 1.1 создайте numpy массив натуральных чисел от 0 до 47
a = np.arange(48) # start, stop, step
print(a)

# 1.2 преобразуйте его в матрицу размером 12x4 
a = a.reshape(12, 4) 
print(a)

# 1.3 преобразуйте эту матрицу в трехмерную матрицу размером 3x4x4
a = a.reshape(3, 4, 4) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


2 . Американские коллеги прислали архив с наблюдениями температуры, но вот незадача: температура там указана в Фаренгейтах. <br>  Формула для перевода: $\frac{C}{5}=\frac{F - 32}{9}$

In [8]:
temps_F = np.array([0, 100, 99.1, 32, 44, 241, 10, 15, 20])

temps_C = ((temps_F - 32) * 5) / 9
print(temps_C)

[-17.77777778  37.77777778  37.27777778   0.           6.66666667
 116.11111111 -12.22222222  -9.44444444  -6.66666667]


In [10]:
# Настройки вывода для numpy
np.set_printoptions(linewidth=110, precision=3)

In [11]:
temps_C

array([-17.778,  37.778,  37.278,   0.   ,   6.667, 116.111, -12.222,  -9.444,  -6.667])

In [12]:
np.round(temps_C, 2)

array([-17.78,  37.78,  37.28,   0.  ,   6.67, 116.11, -12.22,  -9.44,  -6.67])

In [14]:
%precision 1
temps_C

array([-17.8,  37.8,  37.3,   0. ,   6.7, 116.1, -12.2,  -9.4,  -6.7])

In [16]:
np.set_printoptions(threshold=5)

In [17]:
temps_C

array([-17.8,  37.8,  37.3, ..., -12.2,  -9.4,  -6.7], shape=(9,))