## Библиотека numpy

### Практика 1

In [4]:
# загрузите необходимые библиотеки
import numpy as np

### Задачи

Решите следующие задачи без использования циклов, с минимальным количеством строк.

1 . Решите следующие небольшие задачи

In [6]:
# 1.1 создайте numpy массив натуральных чисел от 0 до 47
arr = np.arange(48)
print(arr)
print()

# 1.2 преобразуйте его в матрицу размером 12x4 
matrix2d = arr.reshape(12, 4)
print(matrix2d)
print()

# 1.3 преобразуйте эту матрицу в трехмерную матрицу размером 3x4x4
matrix3d = matrix2d.reshape(3, 4, 4)
print(matrix3d)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]



2 . Американские коллеги прислали архив с наблюдениями температуры, но вот незадача: температура там указана в Фаренгейтах. <br>  Формула для перевода: $\frac{C}{5}=\frac{F - 32}{9}$

In [9]:
temps_F = np.array([0, 100, 99.1, 32, 44, 241, 10, 15, 20])
# ваш код здесь
tempsC = np.round((temps_F - 32) * 5 / 9, 2)
print(tempsC)

[-17.78  37.78  37.28   0.     6.67 116.11 -12.22  -9.44  -6.67]
