In [16]:
# 1. Импортировать NumPy
import numpy as np
np.set_printoptions(linewidth=110, legacy='1.25', precision=2)

In [17]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [18]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
array = np.random.randint(1, 100, size=(10, 10), dtype=np.int64); array

array([[97, 22, 50, 70, 36, 61, 98, 85, 89, 96],
       [ 4, 66, 51, 96, 83, 90, 49, 64, 90, 22],
       [56, 85, 27, 77, 63, 95, 32, 56, 93, 34],
       [75, 99, 56, 15, 40, 27, 48, 23,  3, 48],
       [81, 72, 93, 86,  4, 72,  8, 60, 77, 19],
       [18, 76, 50, 26, 76, 95, 78, 96, 90, 12],
       [ 6, 17, 11, 26, 81, 33, 26, 80,  1, 80],
       [96, 61, 23, 65, 45, 16, 29, 77,  1, 48],
       [93, 83, 26, 39, 77, 14, 97, 68,  4, 26],
       [79,  5, 45,  2, 43,  5, 46, 22, 51, 75]])

In [19]:
# 1.2 Вычислить среднее значение всех элементов массива с помощью np.mean()
mean_all = np.mean(array)
mean_all

52.82

In [20]:
# 1.3 Вычислить среднее значение всех элементов 
# для каждой строки с помощью np.mean() 
# и добавить как новый столбец
mean_rows = np.mean(array, axis=1)
mean_rows
array = np.insert(array.astype(np.float64), 10, mean_rows, axis=1)
array

array([70.4, 61.5, 61.8, 43.4, 57.2, 61.7, 36.1, 46.1, 52.7, 37.3])

array([[97. , 22. , 50. , 70. , 36. , 61. , 98. , 85. , 89. , 96. , 70.4],
       [ 4. , 66. , 51. , 96. , 83. , 90. , 49. , 64. , 90. , 22. , 61.5],
       [56. , 85. , 27. , 77. , 63. , 95. , 32. , 56. , 93. , 34. , 61.8],
       [75. , 99. , 56. , 15. , 40. , 27. , 48. , 23. ,  3. , 48. , 43.4],
       [81. , 72. , 93. , 86. ,  4. , 72. ,  8. , 60. , 77. , 19. , 57.2],
       [18. , 76. , 50. , 26. , 76. , 95. , 78. , 96. , 90. , 12. , 61.7],
       [ 6. , 17. , 11. , 26. , 81. , 33. , 26. , 80. ,  1. , 80. , 36.1],
       [96. , 61. , 23. , 65. , 45. , 16. , 29. , 77. ,  1. , 48. , 46.1],
       [93. , 83. , 26. , 39. , 77. , 14. , 97. , 68. ,  4. , 26. , 52.7],
       [79. ,  5. , 45. ,  2. , 43. ,  5. , 46. , 22. , 51. , 75. , 37.3]])

In [21]:
# 1.4 Вычислить сумму значений всех элементов для каждого столбца с помощью 
# np.sum()и добавить как новую строку, учитывая результат пункта 1.3
sum_cols = np.sum(array, axis=0)
array = np.vstack([array, sum_cols])
array

array([[ 97. ,  22. ,  50. ,  70. ,  36. ,  61. ,  98. ,  85. ,  89. ,  96. ,  70.4],
       [  4. ,  66. ,  51. ,  96. ,  83. ,  90. ,  49. ,  64. ,  90. ,  22. ,  61.5],
       [ 56. ,  85. ,  27. ,  77. ,  63. ,  95. ,  32. ,  56. ,  93. ,  34. ,  61.8],
       [ 75. ,  99. ,  56. ,  15. ,  40. ,  27. ,  48. ,  23. ,   3. ,  48. ,  43.4],
       [ 81. ,  72. ,  93. ,  86. ,   4. ,  72. ,   8. ,  60. ,  77. ,  19. ,  57.2],
       [ 18. ,  76. ,  50. ,  26. ,  76. ,  95. ,  78. ,  96. ,  90. ,  12. ,  61.7],
       [  6. ,  17. ,  11. ,  26. ,  81. ,  33. ,  26. ,  80. ,   1. ,  80. ,  36.1],
       [ 96. ,  61. ,  23. ,  65. ,  45. ,  16. ,  29. ,  77. ,   1. ,  48. ,  46.1],
       [ 93. ,  83. ,  26. ,  39. ,  77. ,  14. ,  97. ,  68. ,   4. ,  26. ,  52.7],
       [ 79. ,   5. ,  45. ,   2. ,  43. ,   5. ,  46. ,  22. ,  51. ,  75. ,  37.3],
       [605. , 586. , 432. , 502. , 548. , 508. , 511. , 631. , 499. , 460. , 528.2]])

In [22]:
# Variant 2
# 1.1 Создаем массив 
mass = np.random.randint(1, 101, size=(10, 10), dtype=np.int64)
print("Исходный массив:")
print(mass)

# 1.2 Вычисляем среднее значение всех элементов
total_mean = np.mean(mass)
print("Среднее значение всех элементов:", total_mean)

# 1.3 Вычисляем среднее по строкам и добавляем как новый столбец
row_means = np.mean(mass, axis=1, keepdims=True)  
matrix_with_means = np.hstack((mass, row_means))  
print("Массив с добавленным столбцом средних по строкам:")
print(matrix_with_means)

# 1.4 Вычисляем сумму по столбцам
col_sum = np.sum(matrix_with_means, axis=0, keepdims=True)
final_mass = np.vstack((matrix_with_means, col_sum))
print("Итоговый массив:")
print(final_mass)

Исходный массив:
[[ 97  14  84   9  87  33  19  49  45  33]
 [ 42   6   5  71  75  46  92  30  30  30]
 [ 80   2  41  94  49  99  63  21  82  48]
 [ 18 100  12  72  40  46  23   1  88  20]
 [ 56  82  67  79  10  17  75  44  93  67]
 [ 12  56   6  17  93  99  15  99  29  45]
 [ 76  79  44   5  55  82  56  43  32  92]
 [ 77  66  43  35  95  97  44  20  91  85]
 [  7  15  31  39  90  49  89  33  99  81]
 [ 17  98  25  37  74  84  56  78   5  35]]
Среднее значение всех элементов: 52.16


(10, 1)

Массив с добавленным столбцом средних по строкам:
[[ 97.   14.   84.    9.   87.   33.   19.   49.   45.   33.   47. ]
 [ 42.    6.    5.   71.   75.   46.   92.   30.   30.   30.   42.7]
 [ 80.    2.   41.   94.   49.   99.   63.   21.   82.   48.   57.9]
 [ 18.  100.   12.   72.   40.   46.   23.    1.   88.   20.   42. ]
 [ 56.   82.   67.   79.   10.   17.   75.   44.   93.   67.   59. ]
 [ 12.   56.    6.   17.   93.   99.   15.   99.   29.   45.   47.1]
 [ 76.   79.   44.    5.   55.   82.   56.   43.   32.   92.   56.4]
 [ 77.   66.   43.   35.   95.   97.   44.   20.   91.   85.   65.3]
 [  7.   15.   31.   39.   90.   49.   89.   33.   99.   81.   53.3]
 [ 17.   98.   25.   37.   74.   84.   56.   78.    5.   35.   50.9]]
Итоговый массив:
[[ 97.   14.   84.    9.   87.   33.   19.   49.   45.   33.   47. ]
 [ 42.    6.    5.   71.   75.   46.   92.   30.   30.   30.   42.7]
 [ 80.    2.   41.   94.   49.   99.   63.   21.   82.   48.   57.9]
 [ 18.  100.   12.   72.   40.   46

#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули. 
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [28]:
# Вариант 1
center_diag = np.array([1, 2, 3, 4, 5, 6, 7])
array_diag = np.diag(center_diag, k=0); array_diag

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [31]:
# Variant 2
res = np.eye(7, dtype=np.int8) * np.arange(1, 8)
res

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [32]:
# Variant 3
# Используя broadcasting

rows, cols = np.indices((7, 7))
rows
cols
matrix = np.where(rows == cols, rows + 1, 0)

print("\nМатрица с broadcasting:")
print(matrix)

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6]])

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])


Матрица с broadcasting:
[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [33]:
# Создаем случайную матрицу 5x7 с целыми числами от 1 до 100
matrix = np.random.randint(1, 101, size=(5, 7))
print(matrix)

# Меняем местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки
matrix[:, [2, 4]] = matrix[:, [4, 2]]
print(matrix)

[[ 3 15 82  3 71 70 77]
 [69 26  8  9  4  3 67]
 [96 92 83 83 77 42 52]
 [11  8 65 56 59 21 46]
 [45 35 41 69 41 63 16]]
[[ 3 15 71  3 82 70 77]
 [69 26  4  9  8  3 67]
 [96 92 77 83 83 42 52]
 [11  8 59 56 65 21 46]
 [45 35 41 69 41 63 16]]
