#### Задача 1
1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

1.2 Вычислить среднее значение всех элементов массива с помощью np.mean()

1.3 Вычислить среднее значение всех элементов для каждой строки с помощью np.mean() и добавить как новый столбец

1.4 Вычислить сумму значений всех элементов для каждого столбца с помощью np.sum()и добавить как новую строку, учитывая результат пункта 1.3

In [1]:
import numpy as np

In [2]:
n = np.random.randint(1, 100, (10, 10), dtype=np.int64)
n2 = n 
print(n)

[[97 40 25 12 34 46 32 23 63  5]
 [40 24 19  7 57 11  8 87 25 72]
 [92 87 74 31 61 98 93 90 52 60]
 [22 98 36 65 68 32 71 20 46 50]
 [57 57 14 10 33  9 68 21 94 77]
 [38 60 46 23 93 58 47  5 18 14]
 [91 76  1 90 12  4 44 31  9 52]
 [79 11 87 61 57 69 45 81 38 20]
 [21 76 28 65 57  4 33 96 78 34]
 [ 3 95 60 75 77  9 51 13  3 19]]


In [3]:
print("среднее массива:", np.mean(n2))

среднее массива: 46.7


In [4]:
srednee_stroka = np.mean(n, axis=1, keepdims=True)
srednee_stroka

array([[37.7],
       [35. ],
       [73.8],
       [50.8],
       [44. ],
       [40.2],
       [41. ],
       [54.8],
       [49.2],
       [40.5]])

In [5]:
new_stolb = np.hstack((n, srednee_stroka))
new_stolb

array([[97. , 40. , 25. , 12. , 34. , 46. , 32. , 23. , 63. ,  5. , 37.7],
       [40. , 24. , 19. ,  7. , 57. , 11. ,  8. , 87. , 25. , 72. , 35. ],
       [92. , 87. , 74. , 31. , 61. , 98. , 93. , 90. , 52. , 60. , 73.8],
       [22. , 98. , 36. , 65. , 68. , 32. , 71. , 20. , 46. , 50. , 50.8],
       [57. , 57. , 14. , 10. , 33. ,  9. , 68. , 21. , 94. , 77. , 44. ],
       [38. , 60. , 46. , 23. , 93. , 58. , 47. ,  5. , 18. , 14. , 40.2],
       [91. , 76. ,  1. , 90. , 12. ,  4. , 44. , 31. ,  9. , 52. , 41. ],
       [79. , 11. , 87. , 61. , 57. , 69. , 45. , 81. , 38. , 20. , 54.8],
       [21. , 76. , 28. , 65. , 57. ,  4. , 33. , 96. , 78. , 34. , 49.2],
       [ 3. , 95. , 60. , 75. , 77. ,  9. , 51. , 13. ,  3. , 19. , 40.5]])

In [6]:
summa_stolb = np.sum(new_stolb, axis=0, keepdims=True)
summa_stolb

array([[540., 624., 390., 439., 549., 340., 492., 467., 426., 403., 467.]])

In [7]:
new_stroka = np.vstack((new_stolb, summa_stolb))
new_stroka

array([[ 97. ,  40. ,  25. ,  12. ,  34. ,  46. ,  32. ,  23. ,  63. ,
          5. ,  37.7],
       [ 40. ,  24. ,  19. ,   7. ,  57. ,  11. ,   8. ,  87. ,  25. ,
         72. ,  35. ],
       [ 92. ,  87. ,  74. ,  31. ,  61. ,  98. ,  93. ,  90. ,  52. ,
         60. ,  73.8],
       [ 22. ,  98. ,  36. ,  65. ,  68. ,  32. ,  71. ,  20. ,  46. ,
         50. ,  50.8],
       [ 57. ,  57. ,  14. ,  10. ,  33. ,   9. ,  68. ,  21. ,  94. ,
         77. ,  44. ],
       [ 38. ,  60. ,  46. ,  23. ,  93. ,  58. ,  47. ,   5. ,  18. ,
         14. ,  40.2],
       [ 91. ,  76. ,   1. ,  90. ,  12. ,   4. ,  44. ,  31. ,   9. ,
         52. ,  41. ],
       [ 79. ,  11. ,  87. ,  61. ,  57. ,  69. ,  45. ,  81. ,  38. ,
         20. ,  54.8],
       [ 21. ,  76. ,  28. ,  65. ,  57. ,   4. ,  33. ,  96. ,  78. ,
         34. ,  49.2],
       [  3. ,  95. ,  60. ,  75. ,  77. ,   9. ,  51. ,  13. ,   3. ,
         19. ,  40.5],
       [540. , 624. , 390. , 439. , 549. , 340. , 492. , 467

#### Задача 2
2.1 Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули. Два варианта решения: с помощью функции np.diag() и без(используя broadcasting).

In [8]:
diag_matrix = np.diag([1, 2, 3, 4, 5, 6, 7])
diag_matrix

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [ ]:
#Задача 3
3.1 Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [138]:
matrix = np.random.randint(1, 101, size=(5, 7))
matrix

array([[36,  8, 84, 42, 51, 29, 21],
       [ 7, 74, 94, 60, 29, 25, 93],
       [79, 28, 65, 63, 80, 71, 64],
       [14,  8, 84, 23, 23, 12, 59],
       [61, 82, 52,  4, 73,  7, 15]])

In [139]:
matrix[:, [2, 4]] = matrix[:, [4, 2]]
matrix

array([[36,  8, 51, 42, 84, 29, 21],
       [ 7, 74, 29, 60, 94, 25, 93],
       [79, 28, 80, 63, 65, 71, 64],
       [14,  8, 23, 23, 84, 12, 59],
       [61, 82, 73,  4, 52,  7, 15]])