In [1]:
# 1. Импортировать NumPy
import numpy as np

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [3]:
# 1.1
arr = np.random.randint(1, 101, size=(10, 10), dtype=np.int64)

# 1.2 о
mean_all = np.mean(arr)  

# 1.3
mean_by_row = np.mean(arr, axis=1).reshape(-1, 1)  
arr_with_mean = np.hstack((arr, mean_by_row))  

# 1.4
sum_by_col = np.sum(arr_with_mean, axis=0)  
final_array = np.vstack((arr_with_mean, sum_by_col)) 

final_array

array([[ 81. ,  28. ,  70. ,  61. ,  83. ,  63. ,   2. ,  56. ,  10. ,
         72. ,  52.6],
       [ 86. ,  71. ,   1. ,  89. ,  47. ,  13. ,  43. ,  58. ,  60. ,
         47. ,  51.5],
       [ 65. ,  81. ,  95. ,  51. ,  75. ,  99. ,  11. ,   9. ,  13. ,
         78. ,  57.7],
       [ 85. ,  97. ,  37. ,  50. ,  33. ,  26. ,  63. ,  84. ,  60. ,
         28. ,  56.3],
       [ 26. ,  58. ,  63. ,   5. ,  17. ,  56. ,  72. ,  73. ,  27. ,
         45. ,  44.2],
       [ 62. ,  25. ,  44. ,  61. ,  57. ,  66. ,  41. ,  86. ,  51. ,
         65. ,  55.8],
       [  7. ,  23. ,  71. ,  35. ,  47. ,  50. ,  77. ,  54. ,  61. ,
         28. ,  45.3],
       [ 12. ,  21. ,   8. ,  26. ,  63. ,   4. ,  68. ,  38. ,  12. ,
         22. ,  27.4],
       [ 50. ,  46. ,  69. ,   3. ,  13. ,  58. ,  21. ,  15. ,  46. ,
         33. ,  35.4],
       [ 80. ,  70. ,   1. ,  39. ,   4. ,  24. ,  11. ,  37. ,  32. ,
         41. ,  33.9],
       [554. , 520. , 459. , 420. , 439. , 459. , 409. , 510

#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули. 
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [7]:
# создаём список от 1 до 7
diagonal_values = np.arange(1, 8)

# создаём диагональную матрицу
matrix_diag = np.diag(diagonal_values)

matrix_diag

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [11]:
# Как использовать BROADCASTING ?

# создаём нулевую матрицу
matrix_diag_2 = np.zeros((7, 7), dtype=int)

# создаём массив индексов
i = np.arange(7)

# записываем значения на диагональ
matrix_diag_2[i, i] = np.arange(1, 8)

matrix_diag_2

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [17]:
np.set_printoptions(linewidth=110)

# создаём случайную матрицу
arr = np.random.randint(1, 101, size=(5, 7))

# меняем 3-й и 5-й столбцы местами
arr[:, [2, 4]] = arr[:, [4, 2]]
arr

array([[81, 80, 95, 51, 69, 26, 64],
       [ 9, 29, 23, 51, 15, 60, 11],
       [ 3, 34, 51, 86, 21, 39, 89],
       [30,  5, 69, 63, 47, 33, 24],
       [16, 43, 29, 80, 40, 53, 27]])