In [1]:
# 1. Импортировать NumPy
import numpy as np

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [71]:
mas = np.random.randint(1, 100, size=(10, 10))
print(mas)
avg_all = np.mean(mas)
print(avg_all)
avg1 = np.mean(mas, axis=1)
print(avg1)
mas = mas.transpose()
mas = np.append(mas, [avg1], axis = 0)
mas = mas.transpose()
print(mas)
sm = np.sum(mas, axis=0)
print(sm)
mas = np.append(mas, [sm], axis=0)
print(mas)

[[47 77 12 91 93 98 48 20 30 73]
 [65 35  1 94 54 40 17 21 46 46]
 [16 27 94 79 83 73 65 97 52 63]
 [47 84 72 90 85 67 23 36 66 39]
 [80 26 70  6 39 74 60 33 57 97]
 [85 75  1  8 13 17  6 47  2 80]
 [58 74 15 15 60 26 28 54 60 11]
 [25 47 33 19 34 28 60 46 17 70]
 [ 4 45 87 49 51 21  5 37 78 15]
 [22 23 43 35 24 87 12 72 10 26]]
46.68
[58.9 41.9 64.9 60.9 54.2 33.4 40.1 37.9 39.2 35.4]
[[47.  77.  12.  91.  93.  98.  48.  20.  30.  73.  58.9]
 [65.  35.   1.  94.  54.  40.  17.  21.  46.  46.  41.9]
 [16.  27.  94.  79.  83.  73.  65.  97.  52.  63.  64.9]
 [47.  84.  72.  90.  85.  67.  23.  36.  66.  39.  60.9]
 [80.  26.  70.   6.  39.  74.  60.  33.  57.  97.  54.2]
 [85.  75.   1.   8.  13.  17.   6.  47.   2.  80.  33.4]
 [58.  74.  15.  15.  60.  26.  28.  54.  60.  11.  40.1]
 [25.  47.  33.  19.  34.  28.  60.  46.  17.  70.  37.9]
 [ 4.  45.  87.  49.  51.  21.   5.  37.  78.  15.  39.2]
 [22.  23.  43.  35.  24.  87.  12.  72.  10.  26.  35.4]]
[449.  513.  428.  486.  536. 

#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули. 
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [105]:
mas = np.arange(7) + 1
mas = np.diag(mas)
print(mas)
mas = np.eye(7, dtype=int)
mas[1,1] = 2
mas[2,2] = 3
mas[3,3] = 4
mas[4,4] = 5
mas[5,5] = 6
mas[6,6] = 7
print(mas)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]
[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [123]:
mas = np.random.randint(1, 100, size=(5,7))
print(mas)
col3 = [mas[0, 2], mas[1, 2], mas[2, 2], mas[3, 2], mas[4, 2]]
print(col3)
col5 = [mas[0, 4], mas[1, 4], mas[2, 4], mas[3, 4], mas[4, 4]]
print(col5)
mas[0,2] = col5[0]
mas[1,2] = col5[1]
mas[2,2] = col5[2]
mas[3,2] = col5[3]
mas[4,2] = col5[4]
mas[0,4] = col3[0]
mas[1,4] = col3[1]
mas[2,4] = col3[2]
mas[3,4] = col3[3]
mas[4,4] = col3[4]
print(mas)

[[11 42 43 63 65 53 79]
 [36 43 13 89  7 60 96]
 [42 65 79 52 31  9 23]
 [83 28 49 16 40 18 73]
 [19 76 72 46 87 89 97]]
[43, 13, 79, 49, 72]
[65, 7, 31, 40, 87]
[[11 42 65 63 43 53 79]
 [36 43  7 89 13 60 96]
 [42 65 31 52 79  9 23]
 [83 28 40 16 49 18 73]
 [19 76 87 46 72 89 97]]
