In [1]:
# 1. Импортировать NumPy
import numpy as np

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [10]:
# Ваш код
import numpy as np
import numpy.random as rand
np.set_printoptions(linewidth=110, legacy="1.25")

In [3]:
mr = np.random.randint(0, 100, (10,10),dtype=np.int64)
mr

array([[47,  6, 96, 70, 50, 72,  8, 57, 27, 10],
       [52, 36, 33, 89, 68, 96, 63, 11, 57, 60],
       [ 1, 53, 79, 80, 26, 72,  2, 35, 66, 86],
       [68, 48, 30, 99, 25, 81, 20, 49, 24, 56],
       [93, 64, 22, 10, 55, 45, 90, 84, 47, 14],
       [19, 24, 41,  3, 41, 36, 61,  5, 40, 73],
       [83,  0, 35, 88,  9, 76,  9, 94, 90, 24],
       [13, 17, 60,  3, 25, 51, 70,  1, 38, 66],
       [64, 44, 91, 95, 20, 58, 90,  3, 34, 41],
       [62, 74,  3, 95,  2, 97,  7, 89, 58, 49]])

In [4]:
mr_mean = np.mean(mr)
print ("Среднее значение всего массива", mr_mean)

Среднее значение всего массива 48.03


In [5]:
mr_str_mean = mr.mean(axis=1)
print ("Среднее значение столбцов массива", mr_str_mean)

Среднее значение столбцов массива [44.3 56.5 50.  50.  52.4 34.3 50.8 34.4 54.  53.6]


In [6]:
mr_ad = np.append(mr, mr_str_mean[:, None], axis=1)
mr_ad

array([[47. ,  6. , 96. , 70. , 50. , 72. ,  8. , 57. , 27. , 10. , 44.3],
       [52. , 36. , 33. , 89. , 68. , 96. , 63. , 11. , 57. , 60. , 56.5],
       [ 1. , 53. , 79. , 80. , 26. , 72. ,  2. , 35. , 66. , 86. , 50. ],
       [68. , 48. , 30. , 99. , 25. , 81. , 20. , 49. , 24. , 56. , 50. ],
       [93. , 64. , 22. , 10. , 55. , 45. , 90. , 84. , 47. , 14. , 52.4],
       [19. , 24. , 41. ,  3. , 41. , 36. , 61. ,  5. , 40. , 73. , 34.3],
       [83. ,  0. , 35. , 88. ,  9. , 76. ,  9. , 94. , 90. , 24. , 50.8],
       [13. , 17. , 60. ,  3. , 25. , 51. , 70. ,  1. , 38. , 66. , 34.4],
       [64. , 44. , 91. , 95. , 20. , 58. , 90. ,  3. , 34. , 41. , 54. ],
       [62. , 74. ,  3. , 95. ,  2. , 97. ,  7. , 89. , 58. , 49. , 53.6]])

In [11]:
new_mas = np.concatenate((mr_ad, mr_ad.sum(axis=0, keepdims=True)), axis=0)
new_mas

array([[ 47. ,   6. ,  96. ,  70. ,  50. ,  72. ,   8. ,  57. ,  27. ,  10. ,  44.3],
       [ 52. ,  36. ,  33. ,  89. ,  68. ,  96. ,  63. ,  11. ,  57. ,  60. ,  56.5],
       [  1. ,  53. ,  79. ,  80. ,  26. ,  72. ,   2. ,  35. ,  66. ,  86. ,  50. ],
       [ 68. ,  48. ,  30. ,  99. ,  25. ,  81. ,  20. ,  49. ,  24. ,  56. ,  50. ],
       [ 93. ,  64. ,  22. ,  10. ,  55. ,  45. ,  90. ,  84. ,  47. ,  14. ,  52.4],
       [ 19. ,  24. ,  41. ,   3. ,  41. ,  36. ,  61. ,   5. ,  40. ,  73. ,  34.3],
       [ 83. ,   0. ,  35. ,  88. ,   9. ,  76. ,   9. ,  94. ,  90. ,  24. ,  50.8],
       [ 13. ,  17. ,  60. ,   3. ,  25. ,  51. ,  70. ,   1. ,  38. ,  66. ,  34.4],
       [ 64. ,  44. ,  91. ,  95. ,  20. ,  58. ,  90. ,   3. ,  34. ,  41. ,  54. ],
       [ 62. ,  74. ,   3. ,  95. ,   2. ,  97. ,   7. ,  89. ,  58. ,  49. ,  53.6],
       [502. , 366. , 490. , 632. , 321. , 684. , 420. , 428. , 481. , 479. , 480.3]])

#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули. 
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [12]:
# Ваш код
mr_diag = np.arange(1,8)
mr_diag

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
mr_full = np.diagflat(mr_diag)
mr_full

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [14]:
#2sposob
mr_zero = np.zeros((7,7))
mr_zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
mr_d = np.arange(1,8)
mr_d

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
mr_zero [range(7),range(7)]=mr_d

In [17]:
mr_zero

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])

#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [ ]:
# Ваш код

In [ ]:
mg = np.random.randint(0, 100, (5,7),dtype=np.int64)
mg

In [ ]:
mq = np.hsplit(mg, 7)

In [ ]:
mgs = np.hstack((mq[0], mq[1], mq[4], mq[3], mq[2], mq[5], mq[6]))
mgs