In [1]:
# 1. Импортировать NumPy
import numpy as np
np.set_printoptions(linewidth=110)

#### Задача 1

**1.1** Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

**1.2** Вычислить среднее значение всех элементов массива с помощью `np.mean()`

**1.3** Вычислить среднее значение всех элементов для каждой строки с помощью `np.mean()` и добавить как новый столбец

**1.4** Вычислить сумму значений всех элементов для каждого столбца с помощью `np.sum()`и добавить как новую строку, учитывая результат пункта `1.3`

In [4]:
array = np.random.randint (1, 100, size=(10, 10), dtype = np.int64)
np.mean (array)
mean_for_row = array.mean(axis=1).reshape(10, 1)
array_new_coloumn= np.append(array, mean_for_row, axis=1)
sum_of_coloumn = array_new_coloumn.sum(axis=0).reshape(1, 11)
array_new_row_included_new_coloumn = np.append(array_new_coloumn, sum_of_coloumn, axis=0)
array_new_row_included_new_coloumn

array([[ 17. ,  29. ,  13. ,  20. ,  64. ,  72. ,   3. ,  66. ,  74. ,  38. ,  39.6],
       [ 62. ,  16. ,  43. ,  24. ,  26. ,  43. ,  54. ,  24. ,  21. ,  46. ,  35.9],
       [ 80. ,  81. ,  97. ,  22. ,  36. ,  37. ,  25. ,  90. ,  81. ,  20. ,  56.9],
       [ 89. ,  13. ,  32. ,  88. ,  39. ,  86. ,   7. ,  77. ,  59. ,  96. ,  58.6],
       [ 15. ,  30. ,  64. ,  25. ,  66. ,  53. ,  48. ,  16. ,   3. ,  71. ,  39.1],
       [ 19. ,  64. ,  98. ,  43. ,  27. ,  83. ,  58. ,  75. ,  84. ,   3. ,  55.4],
       [ 57. ,  58. ,   6. ,  79. ,  33. ,  58. ,  10. ,  74. ,  81. ,  90. ,  54.6],
       [ 20. ,  50. ,  43. ,  62. ,  77. ,  18. ,  79. ,  38. ,  48. ,  18. ,  45.3],
       [ 73. ,  86. ,  46. ,  20. ,  89. ,  19. ,  38. ,  84. ,  62. ,  60. ,  57.7],
       [ 74. ,  85. ,  62. ,  78. ,  73. ,  19. ,  44. ,  71. ,  58. ,  30. ,  59.4],
       [506. , 512. , 504. , 461. , 530. , 488. , 366. , 615. , 571. , 472. , 502.5]])

In [3]:
 np.array([5. ,  51. ,  90. ,  25. ,  14. ,  46. ,  77. ,  37. ,  69. ,  27.]).mean()

np.float64(44.1)

#### Задача 2
**2.1** Создать матрицу 7x7 с значениями `1,2,3,4,5,6,7` по главной диагонали, остальные нули. 
Два варианта решения: с помощью функции `np.diag()` и без(используя _broadcasting_).

In [7]:
# 2
#a)
diagonal =np.arange (1, 8)
matrix = np.diag (diagonal)
matrix

#b)

matrix2 = np.zeros ((7, 7))
matrix2[np.arange(7), np.arange(7)] = np.arange(1, 8)
matrix2


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])

#### Задача 3

**3.1** Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3-ю (индекс 2) и 5-ю (индекс 4) колонки

In [115]:
matrix_3 = np.random.randint (1, 100, size=(5, 7), dtype = np.int64)
matrix_3

array([[75,  6, 51, 80, 37, 54, 23],
       [15, 70, 34, 56, 63, 89, 45],
       [38, 79, 13, 37, 55, 69, 60],
       [89, 62, 31, 63, 97, 36, 16],
       [44,  5,  6, 23, 36, 62, 89]], dtype=int64)

In [116]:
matrix_3 [:, (2, 4)] = matrix_3 [:, (4, 2)]
matrix_3

array([[75,  6, 37, 80, 51, 54, 23],
       [15, 70, 63, 56, 34, 89, 45],
       [38, 79, 55, 37, 13, 69, 60],
       [89, 62, 97, 63, 31, 36, 16],
       [44,  5, 36, 23,  6, 62, 89]], dtype=int64)